In [15]:
################################### NumPy #######################################

import numpy as np # written on C

# multiplication sequence by 2 to work faster in NumPy compared with Python
my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000))

%time my_arr = my_arr * 2
"""CPU times: user 938 μs, sys: 149 μs, total: 1.09 ms
Wall time: 1.1 ms"""

%time my_list = [x * 2 for x in my_list]
"""CPU times: user 12.1 ms, sys: 14.8 ms, total: 26.9 ms
Wall time: 36.4 ms"""


CPU times: user 1.32 ms, sys: 0 ns, total: 1.32 ms
Wall time: 2.13 ms
CPU times: user 12.1 ms, sys: 14.8 ms, total: 26.9 ms
Wall time: 36.4 ms


In [26]:
######################################## 4.1 NDARRAY ############################

import numpy as np

data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data
"""array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])"""
data * 10 
"""array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])"""
data + data
"""array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])"""

# attributes of ndarray
data.shape # size array by axes YX:  (2, 3)
data.dtype # similar types in array
data.ndim # count of dimension

# create ndarray object from any sequence
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1 # array([6. , 7.5, 8. , 0. , 1. ]), type of elements: float64
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
"""array([[1, 2, 3, 4],
       [5, 6, 7, 8]])"""
arr2.ndim # 2 dimension

np.zeros(10) # array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
np.empty((2, 3, 2)) # many garbage here
"""
array([[[2.877995e-316, 0.000000e+000],
        [0.000000e+000, 0.000000e+000],
        [0.000000e+000, 0.000000e+000]],

       [[0.000000e+000, 0.000000e+000],
        [0.000000e+000, 0.000000e+000],
        [0.000000e+000, 0.000000e+000]]])
"""
np.arange(10) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
tuple(range(10))

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)